### ISSUE TITLE
Cannot generate tool execution command

### ISSUE THREAD

**Issue by orviz** [EOSC-synergy/sqaaas-api-server#116]
When composing a pipeline with just a tool from the tooling.json, hadolint in this example:

```
2021-11-04 08:48:59,880 - sqaaas_api.controller - DEBUG - Received request (keyword args): {'body': {'name': 'asdfasdf', 'composer_data': {'services': {}, 'version': '3.7'}, 'config_data': [{'config': {'project_repos': [], 'credentials': []}, 'environment': {}, 'sqa_criteria': {'QC.Sty': {'repos': [{'repo_url': '', 'container': '', 'tools': [{'name': 'hadolint', 'lang': 'dockerfile', 'docs': 'https://github.com/hadolint/hadolint', 'docker': {'image': 'hadolint/hadolint:latest-alpine', 'reviewed': '2021-06-21'}, 'args': [{'type': 'optional', 'description': 'Ignore rules (see https://github.com/hadolint/hadolint#rules)', 'value': '', 'format': 'string', 'selectable': True, 'repeatable': True}]}]}]}}, 'timeout': 600}], 'jenkinsfile_data': {'stages': [{'pipeline_config': {'base_branch': 'https://github.com/jenkins-docs/simple-java-maven-app', 'base_repository': 'master', 'config_file': './.sqa/config.yml', 'credentials_id': 'userpass_dockerhub', 'jepl_validator_docker_image': 'eoscsynergy/jpl-validator:1.1.0'}, 'when': {'branches': ['master']}}]}}, 'request': <Request POST /v1/pipeline >}
2021-11-04 08:48:59,881 - sqaaas_api.controller - DEBUG - Repository ID for pipeline name <asdfasdf>: eosc-synergy/asdfasdf.sqaaas
2021-11-04 08:48:59,881 - sqaaas_api.controller - DEBUG - Using GitHub repository name: eosc-synergy/asdfasdf.sqaaas
2021-11-04 08:48:59,881 - sqaaas_api.controller - DEBUG - Call to ProcessExtraData.set_tool_env() method
2021-11-04 08:48:59,881 - sqaaas_api.controller - DEBUG - No Dockerfile definition found for tool <hadolint>
2021-11-04 08:48:59,881 - sqaaas_api.controller - DEBUG - Changing previous container name <> to <qc.sty_foggy-auburn-kingfisher>
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/connexion/apis/aiohttp_api.py", line 50, in problems_middleware
    response = yield from handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 110, in impl
    return await handler(request)
  File "/usr/local/lib/python3.9/site-packages/connexion/decorators/coroutine_wrappers.py", line 23, in wrapper
    connexion_response = yield from connexion_response
  File "/usr/local/lib/python3.9/site-packages/openapi_server/controllers/utils.py", line 42, in decorated_function
    ret = await f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/openapi_server/controllers/utils.py", line 108, in decorated_function
    ret = await f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/openapi_server/controllers/default_controller.py", line 92, in add_pipeline
    db.add_entry(
  File "/usr/local/lib/python3.9/site-packages/openapi_server/controllers/db.py", line 71, in add_entry
    config_data_list, composer_data, jenkinsfile, commands_script_list = JePLUtils.compose_files(
  File "/usr/local/lib/python3.9/site-packages/openapi_server/controllers/jepl.py", line 98, in compose_files
    config_data_list, composer_data, commands_script_list = ctls_utils.process_extra_data(
  File "/usr/local/lib/python3.9/site-packages/openapi_server/controllers/utils.py", line 457, in process_extra_data
    service_name = ProcessExtraData.set_tool_env(
  File "/usr/local/lib/python3.9/site-packages/openapi_server/controllers/utils.py", line 364, in set_tool_env
    cmd_list.append(arg['option'])
KeyError: 'option'

```

**Comment by orviz** [comment]
The error was related to an error in the `hadolint` tool definition, it was missing the property `option`
