### ISSUE TITLE
Allow more than one different repo within criterion definition

### ISSUE THREAD

**Issue by orviz** [EOSC-synergy/sqaaas-api-server#140]
Although `repos` is defined as a list of dicts (see example below), it **does not consider more than 1 repository**. If more than one is provided, it (wrongly) only considers the last one (this goes in sync with the web, see 'Dependency issues')
```json
  "sqa_criteria": {
    "QC.Sty": {
      "repos": [
        {
          "repo_url": "",
          "container": "",
          "tools": [
(..)
```

### Request payload
```
{                                                                         
    "name": "safdadsf",
    "composer_data": {
        "services": {},
        "version": "3.7"
    },
    "config_data": [
        {
            "config": {
                "project_repos": [],
                "credentials": []
            },
            "environment": {},
            "sqa_criteria": {
                "QC.Sty": {
                    "repos": [
                        {
                            "repo_url": "https://github.com/foo",
                            "container": "",
                            "tools": [
                                {
                                    "name": "licensee",
                                    "lang": "default",
                                    "docs": "sth sthmore sthelse",
                                    "docker": {
                                        "dockerfile": "QC.Lic/licensee/Dockerfile",
                                        "reviewed": "2021-11-23"
                                    },
                                    "args": [
                                        {
                                            "type": "subcommand",
                                            "description": "Detect the license of the given project",
                                            "value": "detect",
                                            "selectable": false,
                                            "args": [
                                                {
                                                    "type": "positional",
                                                    "description": "Path to project's license",
                                                    "value": ".",
                                                    "selectable": false
                                                }
                                            ]
                                        },
                                        {
                                            "type": "optional",
                                            "description": "JSON output",
                                            "option": "--json",
                                            "selectable": false
                                        }
                                    ],
                                    "reporting": {
                                        "plugin": {
                                            "name": "licensee",
                                            "threshold": 50
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            "repo_url": "https://github.com/bar",
                            "container": "",
                            "tools": [
                                {
                                    "name": "licensee",
                                    "lang": "default",
                                    "docs": "sth sthmore sthelse",
                                    "docker": {
                                        "dockerfile": "QC.Lic/licensee/Dockerfile",
                                        "reviewed": "2021-11-23"
                                    },
                                    "args": [
                                        {
                                            "type": "subcommand",
                                            "description": "Detect the license of the given project",
                                            "value": "detect",
                                            "selectable": false,
                                            "args": [
                                                {
                                                    "type": "positional",
                                                    "description": "Path to project's license",
                                                    "value": ".",
                                                    "selectable": false
                                                }
                                            ]
                                        },
                                        {
                                            "type": "optional",
                                            "description": "JSON output",
                                            "option": "--json",
                                            "selectable": false
                                        }
                                    ],
                                    "reporting": {
                                        "plugin": {
                                            "name": "licensee",
                                            "threshold": 50
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                }
            },
            "timeout": 600
        }
    ],
    "jenkinsfile_data": {
        "stages": [
            {
                "pipeline_config": {
                    "base_branch": "https://github.com/jenkins-docs/simple-java-maven-app",
                    "base_repository": "master",
                    "config_file": "./.sqa/config.yml",
                    "credentials_id": "userpass_dockerhub",
                    "jepl_validator_docker_image": "eoscsynergy/jpl-validator:1.1.0"
                },
                "when": {
                    "branches": [
                        "master"
                    ]
                }
            }
        ]
    }
}
```

### Exception from API server
```
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/connexion/apis/aiohttp_api.py", line 50, in problems_middleware
    response = yield from handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 110, in impl
    return await handler(request)
  File "/usr/local/lib/python3.9/site-packages/connexion/decorators/coroutine_wrappers.py", line 23, in wrapper
    connexion_response = yield from connexion_response
  File "/usr/local/lib/python3.9/site-packages/openapi_server/controllers/utils.py", line 59, in decorated_function
    ret = await f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/openapi_server/controllers/utils.py", line 125, in decorated_function
    ret = await f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/openapi_server/controllers/default_controller.py", line 97, in add_pipeline
    db.add_entry(
  File "/usr/local/lib/python3.9/site-packages/openapi_server/controllers/db.py", line 74, in add_entry
    config_data_list, composer_data, jenkinsfile, commands_script_list, tool_criteria_map = JePLUtils.compose_files(
  File "/usr/local/lib/python3.9/site-packages/openapi_server/controllers/jepl.py", line 99, in compose_files
    config_data_list, composer_data, commands_script_list, tool_criteria_map = ctls_utils.process_extra_data(
  File "/usr/local/lib/python3.9/site-packages/openapi_server/controllers/utils.py", line 575, in process_extra_data
    repo_name = project_repos_mapping[repo_url]['name']
KeyError: 'https://github.com/foo'
```

### Dependency issues
- In case the `when` property is used, there is no point in having multiple repositories under `<repos>` since the `when` is applied in the scope of the whole JePL dynamic stages. Whenever this happens, multiple `config.yml` have to be produced (one per repository with `when` clause defined).
- `tools` are currently passed within the repo, but since it applies to the criterion, it might be put right beneath the criterion (sth like: `{ "QC.Sty": { "repos": [], "tools": [] }`
- The [sqaaas-web](https://github.com/eosc-synergy/sqaaas-web) does not compose request payloads with more than one repo, even if selected. It only adds the last repo to the payload. this needs to be fixed when the current issue gets solved

**Consider to turn this issue into a milestone**

**Comment by orviz** [comment]
Addressed in #157
