### ISSUE TITLE
/status fails when it is not requested before Jenkins job is completed + 5 minutes

### ISSUE THREAD

**Issue by orviz** [EOSC-synergy/sqaaas-api-server#167]
The first time `/status` is requested after a `/run` it uses the Jenkins queue item, but this item is removed 5 minutes after the job completion (see [build_job API doc](https://python-jenkins.readthedocs.io/en/latest/api.html#jenkins.Jenkins.build_job)). Therefore, `/status` fails if the first time it is requested is after the queue item is deleted from Jenkins.

```console
2022-01-13 10:26:37,819 - sqaaas.api.controller - DEBUG - Received request (keyword args): {'pipeline_id': '18844b65-027c-4be0-8f33-541a6cd697ac', 'request': <Request GET /v1/pipeline/18844b65-027c-4be0-8f33-541a6cd697ac/status >}
2022-01-13 10:26:37,832 - sqaaas.api.controller - DEBUG - Pipeline <18844b65-027c-4be0-8f33-541a6cd697ac> found in DB
2022-01-13 10:26:37,832 - sqaaas.api.controller - DEBUG - Running decorated method <get_pipeline_status>
2022-01-13 10:26:37,841 - sqaaas.api.controller.db - DEBUG - Loading pipeline <18844b65-027c-4be0-8f33-541a6cd697ac> from DB
2022-01-13 10:26:38,730 - sqaaas.api.controller - ERROR - (Jenkins) queue number[103586] does not exist
2022-01-13 10:26:38,731 - sqaaas.api.controller - ERROR - Unsuccessful request to upstream service API
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/jenkins/__init__.py", line 575, in jenkins_request
    return self._response_handler(
  File "/usr/local/lib/python3.9/site-packages/jenkins/__init__.py", line 536, in _response_handler
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://jenkins.eosc-synergy.eu/queue/item/103586/api/json?depth=0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/jenkins/__init__.py", line 616, in get_queue_item
    response = self.jenkins_open(requests.Request('GET', url))
  File "/usr/local/lib/python3.9/site-packages/jenkins/__init__.py", line 557, in jenkins_open
    return self.jenkins_request(req, add_crumb, resolve_auth).text
  File "/usr/local/lib/python3.9/site-packages/jenkins/__init__.py", line 589, in jenkins_request
    raise NotFoundException('Requested item could not be found')
jenkins.NotFoundException: Requested item could not be found
```

**Comment by orviz** [comment]
Released in [1.2.0](https://github.com/EOSC-synergy/sqaaas-api-server/releases/tag/1.2.0)
